# Generated by Django 4.2 on 2023-05-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=255)),
                ('id_name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor_number', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('type_of', models.CharField(max_length=255)),
                ('other', models.TextField()),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
