# Generated by Django 4.2 on 2023-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='id_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
