# Generated by Django 4.2 on 2023-05-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('ts', models.CharField(max_length=255)),
                ('id_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=255)),
                ('floor_number', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('type_of', models.CharField(max_length=255)),
                ('other', models.TextField()),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
